services:
  frontend:
    build:
      context: ./frontend/beCompliant
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    environment:
      - TZ=Europe/Oslo
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=kontrollere
      - DB_USER=insert_username_here
      - DB_PASSWORD=password_here
      - AIRTABLE_ACCESS_TOKEN=insert_token_here
    volumes:
      - type: bind
        source: ./conf/
        target: /app/conf/
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
